language: java
dist: trusty
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  app: "keenio-gateway"
  on:
    all_branches: true
  api_key:
    secure: HNN7sjSKgsf0WmhQUAH2OAKdKSnTUYx26f8vm0TxryTyW4LNK58DXYOMgzjeUN1ovVRvcyHk4B4ZDjtVi1pc2M+U9Htd5OIbbgI6cHWkrEblHCjhOdyvP099bMNbKDgwS6b0/vo1TcQF9Y169qsZe6cD8PZAfrrMHOxMOE56JFhBjJDWjRit7ttLKuRjm/rPhnhnNXI2VVk6Dik0f0ulGFKy3g+x3V+lhaAT8ztatHzFmwJgHkU23kq5RRwlU8SeX/FEWEj6D28UQvAhHH071MMNB3jIjvIEhEKihPObgdATiuceUkAq7/pu8Lo3cUVgyEdNI+byAGPuSUanCjQYJTbJbKDGM0WFLzQqiTUAnkfJT0RcBscwWAmWVurvoVFupnwvhYKmX1YAP0NGe9K2SjLKJ5cusWa1g3pJZDl/nymqODOfRQQebVMtfYIATfT0+ljJ3QbC+2yWBiVHwfvql5yumNPXEBoJ6rvfhRpoBjfzPR8FnD1STe3NPlmteFqiBZ/Nz9C/RwAAD6LbqfrkcDEL8SQcBdjJCZnNLijF1Ikfz7SOK0E/umsmb8ZrvM1kI7Yt6Iefm9/lOoplQ5+Hyos00F4aQQTnTRzIQTv+HSNY94Z0OY9A072wCLh7hBpUL1ZJAP0UTLFOUA+xicohn6VizWdP8mhuPVPd74WljuI=
